spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///oakley_data?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: toortoor

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.chenxing.domain
